---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-cert-manager-webhook-hetzner
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-cert-manager-webhook-hetzner:read-secrets
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-cert-manager-webhook-hetzner:domain-solver
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
rules:
  - apiGroups:
      - acme.hetzner.com
    resources:
      - "*"
    verbs:
      - create
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-cert-manager-webhook-hetzner:read-secrets
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snapshot-cert-manager-webhook-hetzner:read-secrets
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: snapshot-cert-manager-webhook-hetzner
    namespace: integrations
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-cert-manager-webhook-hetzner:auth-delegator
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: snapshot-cert-manager-webhook-hetzner
    namespace: integrations
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-cert-manager-webhook-hetzner:domain-solver
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snapshot-cert-manager-webhook-hetzner:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-cert-manager-webhook-hetzner:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: snapshot-cert-manager-webhook-hetzner
    namespace: integrations
---
# Source: cert-manager-webhook-hetzner/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: snapshot-cert-manager-webhook-hetzner
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app: cert-manager-webhook-hetzner
    release: snapshot
---
# Source: cert-manager-webhook-hetzner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-cert-manager-webhook-hetzner
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-hetzner
      release: snapshot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cert-manager-webhook-hetzner
        release: snapshot
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: snapshot-cert-manager-webhook-hetzner
      containers:
        - name: cert-manager-webhook-hetzner
          image: "docker.io/hetzner/cert-manager-webhook-hetzner:v0.6.5" # x-releaser-pleaser-version
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            - name: GROUP_NAME
              value: "acme.hetzner.com"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: certs
          secret:
            secretName: snapshot-cert-manager-webhook-hetzner-webhook-tls
---
# Source: cert-manager-webhook-hetzner/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.hetzner.com
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "integrations/snapshot-cert-manager-webhook-hetzner-webhook-tls"
spec:
  group: acme.hetzner.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: snapshot-cert-manager-webhook-hetzner
    namespace: integrations
  version: v1alpha1
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snapshot-cert-manager-webhook-hetzner-ca
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  secretName: snapshot-cert-manager-webhook-hetzner-ca
  duration: 43800h # 5y
  issuerRef:
    name: snapshot-cert-manager-webhook-hetzner-selfsign
  commonName: "ca.cert-manager-webhook-hetzner.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snapshot-cert-manager-webhook-hetzner-webhook-tls
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  secretName: snapshot-cert-manager-webhook-hetzner-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: snapshot-cert-manager-webhook-hetzner-ca
  dnsNames:
    - snapshot-cert-manager-webhook-hetzner
    - snapshot-cert-manager-webhook-hetzner.integrations
    - snapshot-cert-manager-webhook-hetzner.integrations.svc
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: snapshot-cert-manager-webhook-hetzner-selfsign
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: snapshot-cert-manager-webhook-hetzner-ca
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  ca:
    secretName: snapshot-cert-manager-webhook-hetzner-ca
---
# Source: cert-manager-webhook-hetzner/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snapshot-cert-manager-webhook-hetzner
  namespace: "integrations"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-0.6.5 # x-releaser-pleaser-version
    release: snapshot
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: cert-manager-webhook-hetzner
      release: snapshot
  endpoints:
    - port: metrics
      path: /metrics
