name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    name: e2e k8s-${{ matrix.k8s }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Continue tests matrix if a flaky run occurs.
      matrix:
        k8s:
          - 1.32
          - 1.33
          - 1.34

    permissions:
      id-token: write

    env:
      KUBERNETES_VERSION: ${{ matrix.k8s }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: hetznercloud/tps-action@main

      - name: Install test tools
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

      - name: Setup tests
        run: make e2e-setup

      - name: Run tests
        run: make e2e-coverage

      - name: upload coverage reports to codecov
        if: >
          !startswith(github.head_ref, 'renovate/') &&
          !startswith(github.head_ref, 'releaser-pleaser--')
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.codecov_token }}
